package api

import (
	"net/http"

	"immich-go/internal/domain"
)

// PersonResponse is the wire shape of GET /api/people entries.
type PersonResponse struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	FaceCount        int    `json:"faceCount"`
	ThumbnailAssetID string `json:"thumbnailAssetId"`
	IsHidden         bool   `json:"isHidden"`
	IsFavorite       bool   `json:"isFavorite"`
}

// listPeople returns the face clusters (people) generated by DBSCAN over
// the DuckDB face_search table.
func (s *Server) listPeople(w http.ResponseWriter, r *http.Request) {
	a := caller(w, r)
	if a == nil {
		return
	}
	if !s.requirePermission(w, r, "person.read") {
		return
	}
	persons, err := s.app.Vectors.ListPersons(r.Context(), a.User.ID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	out := make([]PersonResponse, 0, len(persons))
	for _, p := range persons {
		out = append(out, PersonResponse{
			ID:               p.ID,
			Name:             p.Name,
			FaceCount:        p.FaceCount,
			ThumbnailAssetID: p.ThumbnailAssetID,
			IsHidden:         p.IsHidden,
			IsFavorite:       p.IsFavorite,
		})
	}
	writeJSON(w, http.StatusOK, out)
}

// DuplicateGroup mirrors the upstream DuplicateResponseDto shape.
type DuplicateGroup struct {
	ID             string          `json:"id"`
	DuplicateCount int             `json:"duplicateCount"`
	Assets         []AssetResponse `json:"assets"`
}

// listDuplicates groups the owner's assets by duplicateId (assigned by the
// duplicateDetection job over DuckDB CLIP embeddings).
func (s *Server) listDuplicates(w http.ResponseWriter, r *http.Request) {
	a := caller(w, r)
	if a == nil {
		return
	}
	if !s.requirePermission(w, r, "asset.read") {
		return
	}
	assets, err := s.app.Store.Assets().ListForOwner(r.Context(), a.User.ID)
	if err != nil {
		storeError(w, err)
		return
	}
	groups := map[string][]*domain.Asset{}
	for _, asset := range assets {
		if asset.DeletedAt == nil && asset.DuplicateID != nil {
			groups[*asset.DuplicateID] = append(groups[*asset.DuplicateID], asset)
		}
	}
	out := []DuplicateGroup{}
	for id, members := range groups {
		if len(members) < 2 {
			continue
		}
		g := DuplicateGroup{ID: id, DuplicateCount: len(members)}
		for _, m := range members {
			g.Assets = append(g.Assets, s.assetResponse(m, false))
		}
		out = append(out, g)
	}
	writeJSON(w, http.StatusOK, out)
}
