package api

import (
	"net/http"

	"immich-go/internal/domain"
)

// PersonResponse is the wire shape of GET /api/people entries.
type PersonResponse struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	FaceCount        int    `json:"faceCount"`
	ThumbnailAssetID string `json:"thumbnailAssetId"`
	IsHidden         bool   `json:"isHidden"`
	IsFavorite       bool   `json:"isFavorite"`
}

// listPeople returns the face clusters (people) generated by DBSCAN over
// the DuckDB face_search table.
func (s *Server) listPeople(w http.ResponseWriter, r *http.Request) {
	a := caller(w, r)
	if a == nil {
		return
	}
	if !s.requirePermission(w, r, "person.read") {
		return
	}
	persons, err := s.app.Vectors.ListPersons(r.Context(), a.User.ID)
	if err != nil {
		s.writeInternal(w, err)
		return
	}
	out := make([]PersonResponse, 0, len(persons))
	for _, p := range persons {
		out = append(out, PersonResponse{
			ID:               p.ID,
			Name:             p.Name,
			FaceCount:        p.FaceCount,
			ThumbnailAssetID: p.ThumbnailAssetID,
			IsHidden:         p.IsHidden,
			IsFavorite:       p.IsFavorite,
		})
	}
	writeJSON(w, http.StatusOK, out)
}

// DuplicateGroup mirrors the upstream DuplicateResponseDto shape.
type DuplicateGroup struct {
	ID             string          `json:"id"`
	DuplicateCount int             `json:"duplicateCount"`
	Assets         []AssetResponse `json:"assets"`
}

// listDuplicates groups the owner's assets by duplicateId (assigned by the
// duplicateDetection job over DuckDB CLIP embeddings). ?exact=true keeps
// only the members sharing an identical checksum — MT Photos'
// MD5-style exact-duplicate filter (immich-go extension); each checksum
// class with two or more members becomes its own group.
func (s *Server) listDuplicates(w http.ResponseWriter, r *http.Request) {
	a := caller(w, r)
	if a == nil {
		return
	}
	if !s.requirePermission(w, r, "asset.read") {
		return
	}
	exact := r.URL.Query().Get("exact") == "true"
	assets, err := s.app.Store.Assets().ListForOwner(r.Context(), a.User.ID)
	if err != nil {
		s.storeError(w, err)
		return
	}
	groups := map[string][]*domain.Asset{}
	for _, asset := range assets {
		if asset.DeletedAt == nil && asset.DuplicateID != nil {
			groups[*asset.DuplicateID] = append(groups[*asset.DuplicateID], asset)
		}
	}
	out := []DuplicateGroup{}
	for id, members := range groups {
		if len(members) < 2 {
			continue
		}
		if exact {
			for _, class := range groupByChecksum(members) {
				out = append(out, s.duplicateGroupFor(r, id, class))
			}
			continue
		}
		out = append(out, s.duplicateGroupFor(r, id, members))
	}
	writeJSON(w, http.StatusOK, out)
}

func (s *Server) duplicateGroupFor(r *http.Request, id string, members []*domain.Asset) DuplicateGroup {
	g := DuplicateGroup{ID: id, DuplicateCount: len(members)}
	for _, m := range members {
		g.Assets = append(g.Assets, s.assetResponse(r.Context(), m, false))
	}
	return g
}

// groupByChecksum buckets the members by identical checksum, keeping only
// classes with two or more members.
func groupByChecksum(members []*domain.Asset) [][]*domain.Asset {
	classes := map[string][]*domain.Asset{}
	for _, m := range members {
		key := string(m.Checksum)
		classes[key] = append(classes[key], m)
	}
	var out [][]*domain.Asset
	for _, class := range classes {
		if len(class) >= 2 {
			out = append(out, class)
		}
	}
	return out
}
